#!/bin/bash

replace_string_in_file() {
  assurefilename=$1
  assuresearchString=$2
  assurereplaceString=$3

  re="s#^.*$assuresearchString.*#$assurereplaceString#"
  sed -i "${re}" "$assurefilename"
  (( "$?" == "0" )) ||
  echo "Could not execute execute sed command replace $assuresearchString with $assurereplaceString in file $assurefilename, terminating install."
}
ymlFile="cf-openstack-tiny.yml"
ymlFolder="${HOME}/workspace/deployments/cf-boshworkspace/"

DIRECTOR_UUID=$(cat ${ymlFolder}deployments/${ymlFile} | grep director_uuid | awk '{print $2}')
NATS_HOST=$(cat ${ymlFolder}.deployments/${ymlFile} | grep nats -A 1 | grep address | awk '{print $2}')
NATS_PASSWORD=$(cat ${ymlFolder}deployments/${ymlFile} | grep " secret"  | awk '{print $2}')
DOMAIN=$(cat ${ymlFolder}deployments/${ymlFile} | grep " domain"  | awk '{print $2}')
EXTERNAL_HOST="cf-containers-broker.${DOMAIN}"
CF_API_URL="http://api.${DOMAIN}"
OS_AUTHURL=$(cat ${ymlFolder}deployments/${ymlFile} | grep " auth_url"  | awk '{print $2}')
OS_TENANT=$(cat ${ymlFolder}deployments/${ymlFile} | grep " tenant"  | awk '{print $2}')
OS_USERNAME=$(cat ${ymlFolder}deployments/${ymlFile} | grep " username"  | awk '{print $2}')
OS_APIKEY=$(cat ${ymlFolder}deployments/${ymlFile} | grep " api_key"  | awk '{print $2}')
IPMASK=$(cat ${ymlFolder}deployments/${ymlFile} | grep " ipmask"  | awk '{print $2}')


echo "DIRECTOR_UUID:                            ${DIRECTOR_UUID}"
echo "OS_AUTHURL:                               ${OS_AUTHURL}"
echo "OS_TENANT:                                ${OS_TENANT}"
echo "OS_USERNAME:                              ${OS_USERNAME}"
echo "OS_APIKEY:                                ${OS_APIKEY}"
echo "CF_API_URL:                               ${CF_API_URL}"
echo "EXTERNAL_HOST:                            ${EXTERNAL_HOST}"
echo "NATS_HOST:                                ${NATS_HOST}"
echo "SUBNET_ID:                                Get this from OpenStack > Project > Networks > 'Internal Net' > 'docker-services-subnet' > Network ID"
echo "IPMASK:                                   ${IPMASK}"
echo "NATS_PASSWORD:                            ${NATS_PASSWORD}"

filename="/home/ubuntu/workspace/deployments/docker-services-boshworkspace/deployments/docker-openstack.yml"
cp "${filename}" "${filename}.orig"
replace_string_in_file $filename "director_uuid: DIRECTOR_UUID"      "director_uuid: ${DIRECTOR_UUID}"
replace_string_in_file $filename "  cf_api_url: CF_API_URL"          "  cf_api_url: ${CF_API_URL}"
replace_string_in_file $filename "    host: EXTERNAL_HOST"           "    host: ${EXTERNAL_HOST}"
replace_string_in_file $filename "    password: NATS_PASSWORD"       "    password: ${NATS_PASSWORD}"
replace_string_in_file $filename "    - NATS_HOST"                   "    - ${NATS_HOST}"
replace_string_in_file $filename "  ipmask: \"IPMASK\""              "  ipmask: ${IPMASK}"
replace_string_in_file $filename "  domain: CF_DOMAIN"               "  domain: ${DOMAIN}"


echo "*********"
echo "$filename has been updated, remember to update the SUBNET_ID"
