meta:
  nats: (( merge || meta.nats ))
  domain: (( merge ))

networks: (( merge ))

meta:
  release:
    docker: docker
  env_name: (( merge || "env-name" ))

jobs:
  - name: docker
    templates:
      - name: docker
        release: docker
      - name: cf-containers-broker
        release: docker
      - name: containers
        release: docker
    instances: 1
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]
        static_ips: (( static_ips(1, 2, 3, 4, 5) ))
    properties:
      containers:
        - name: registrator
          image: "gliderlabs/registrator:v6"
          memory: "256m"
          command: (( "-resync 3600 -ip " jobs.docker.networks.default.static_ips.[0] " consul://cdh-master-0.node.consul:8080" ))
          volumes:
            - "/var/vcap/data/sys/run/docker:/tmp/docker"
          env_vars:
            - "DOCKER_HOST=unix:///tmp/docker/docker.sock"
