meta:
  nats: (( merge || meta.nats ))
  domain: (( merge ))

networks: (( merge ))

jobs:
  - name: docker
    templates:
      - name: docker
        release: docker
      - name: cf-containers-broker
        release: docker
      - name: containers
        release: docker
    instances: 1
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]
        static_ips: (( static_ips(1, 2, 3, 4, 5) ))
    properties:
      containers:
        - name: authproxy
          image: "quay.io/trustedanalytics/auth-proxy"
          memory: "256m"
          bind_ports:
            - "8080:8080"
          env_vars:
            - (( "DOMAIN=" meta.domain ))
            - (( "CF_API=cf-api." meta.domain ))
            - (( "NATS_URL=nats://"  meta.nats.user ":" meta.nats.password "@" meta.nats.machines.[0] ":4222" ))
            - (( "ROUTE_HOST=" jobs.docker.networks.default.static_ips.[0] ))
            - (( "TOKEN_KEY_URL=http://uaa." meta.domain "/token_key" ))
            - "ROUTE_PORT=8080"
            - "DOCKER_HOST=unix:///tmp/docker/docker.sock"
