meta:
  nats: (( merge || meta.nats ))
  domain: (( merge ))

networks: (( merge ))

meta:
  release:
    docker: docker
  env_name: (( merge || "env-name" ))

jobs:
  - name: docker
    templates:
      - name: docker
        release: docker
      - name: cf-containers-broker
        release: docker
      - name: containers
        release: docker
    instances: 1
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]
        static_ips: (( static_ips(1, 2, 3, 4, 5) ))
    properties:
      containers:
        - name: registrator
          image: "gliderlabs/registrator:v6"
          memory: "256m"
          command: (( "-resync 3600 -ip " jobs.docker.networks.default.static_ips.[0] " consul://cdh-master-0.node.consul:8080" ))
          volumes:
            - "/var/vcap/data/sys/run/docker:/tmp/docker"
          env_vars:
            - "DOCKER_HOST=unix:///tmp/docker/docker.sock"
        - name: h2oprovisioner
          image: "quay.io/trustedanalytics/h2o-provisioner"
          memory: "1024m"
          bind_ports:
            - "9876:8080"
            - "54310-54329:54310-54329"
          env_vars:
            - "DRIVER_PORT_LOWER=54310"
            - "DRIVER_PORT_HIGHER=54329"
            - (( "DRIVER_IP=" jobs.docker.networks.default.static_ips.[0] ))
            - "KRB_KDC=cdh-manager-0.node.consul"
            - "KRB_REALM=CLOUDERA"
            - "KRB_USER=cf"
            - "KRB_PASSWORD=cf1"
